<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Generated by Apache Maven Doxia at 18-abr-2011 -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>develenv-
   <?php
      $develenvVersion=exec('cat index.html |grep "projectVersion"|sed s:".*\: ":"":g|sed s:"<.*":"":g');
     echo  $develenvVersion;
   ?></title>
    <style type="text/css" media="all">
      @import url("./css/maven-base.css");
      @import url("./css/maven-theme.css");
      @import url("./css/site.css");
    </style>
    <link rel="stylesheet" href="./css/print.css" type="text/css" media="print" />
      <meta name="author" content="Carlos Enrique Gómez Gómez" />
    <meta name="Date-Revision-yyyymmdd" content="20110418" />
    <meta http-equiv="Content-Language" content="es" />
    <?php
  $downloadArtifact=htmlspecialchars($_GET["artifact"]);
?>                                                  
<script type="text/javascript">
 document.domain="softwaresano.com";
   var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-8116005-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
                      
  </head>
  <body class="composite">
    <div id="banner">
                  <a href="http://www.softwaresano.com" id="bannerLeft">
                                                <script type="text/javascript" src="http://www.softwaresano.com/widgets/head.php"></script><script type="text/javascript" src="/widgets/head.php"></script>
                </a>
                    <div class="clear">
        <hr/>
      </div>
    </div>
    <div id="breadcrumbs">
            
        
                <div class="xleft">
        <span id="publishDate">Publicado el: <?php
        $publishDate=exec('cat index.html |grep "Publicado el:"|sed s:".*\: ":"":g|sed s:"<.*":"":g');
        echo  $publishDate;?></span>
                  &nbsp;| <span id="projectVersion">Versión:    <?php echo  $develenvVersion;
   ?></span>
                      </div>
            <div class="xright">                    <a href="team-list.html" title="Contacto">Contacto</a>
            |
                        <a href="http://develenv.softwaresano.com" class="externalLink" title="Blog">Blog</a>
            |
                        <a href="maven-repositories.html" title="Repositorios de maven">Repositorios de maven</a>
            |
                        <a href="/sites/" class="externalLink" title="Sites">Sites</a>
            |
                        <a href="/hudson/" class="externalLink" title="Jenkins">Jenkins</a>
            |
                        <a href="/sonar" class="externalLink" title="Sonar">Sonar</a>
            |
                        <a href="/nexus" class="externalLink" title="Nexus">Nexus</a>
            |
                        <a href="/selenium" class="externalLink" title="Selenium">Selenium</a>
      </div>
      <div class="clear">
        <hr/>
      </div>
    </div>
    <div id="leftColumn">
      <div id="navcolumn">
             
        
                                <h5>Descargas</h5>
                  <ul>
                  <li class="none">
                          <a href="downloads/releases.html" title="Releases">Releases</a>
            </li>
	    <li class="none">

                          <a href="virtualMachines.html" title="Máquina Virtual con develenv">Máquina Virtual con develenv</a>
            </li>
                  <li class="none">
                          <a href="changes-report.html" title="Release Notes">Release Notes</a>
            </li>
                  <li class="none">
                          <a href="license.html" title="Licencia">Licencia</a>
            </li>
          </ul>
                       <h5>develenv</h5>
                  <ul>
                  <li class="none">
                          <a href="index.html" title="Introducción">Introducción</a>
            </li>
                  <li class="none">
                          <a href="development.html" title="Compilación">Compilación</a>
            </li>
                  <li class="none">
                          <a href="installation.html" title="Instalación">Instalación</a>
            </li>
                  <li class="none">
                          <a href="administrationGuide.html" title="Manual del administrador">Manual del administrador</a>
            </li>
                  <li class="none">
                          <a href="plugins.html" title="Plugins">Plugins</a>
            </li>
                  <li class="none">
                          <a href="samples.html" title="Ejemplos">Ejemplos</a>
            </li>
                  <li class="none">
                          <a href="improvements.html" title="Futuros desarrollos">Futuros desarrollos</a>
            </li>
          </ul>
                       <h5>Desarrollo</h5>
                  <ul>
                  <li class="none">
                          <a href="source-repository.html" title="Fuentes">Fuentes</a>
            </li>
                  <li class="none">
                          <a href="integration.html" title="Integración continua">Integración continua</a>
            </li>
                  <li class="none">
                          <a href="changelog.html" title="Control de cambios">Control de cambios</a>
            </li>
                  <li class="none">
                          <a href="improvements.html" title="Futuras Mejoras">Futuras Mejoras</a>
            </li>
          </ul>
                       <h5>Documentación del proyecto</h5>
                  <ul>
                                                                                                                                                                                                                                                                                            <li class="collapsed">
                          <a href="project-info.html" title="Información del proyecto">Información del proyecto</a>
                  </li>
                                                                                                                                            <li class="collapsed">
                          <a href="project-reports.html" title="Informes del proyecto">Informes del proyecto</a>
                  </li>
          </ul>
                                 <h5>Módulos</h5>
                  <ul>
                  <li class="none">
                          <a href="./developer/index.html" title="developer">developer</a>
            </li>
                  <li class="none">
                          <a href="./nexus/index.html" title="nexus">nexus</a>
            </li>
                  <li class="none">
                          <a href="./sonar/index.html" title="sonar">sonar</a>
            </li>
                  <li class="none">
                          <a href="./hudson/index.html" title="hudson">hudson</a>
            </li>
                  <li class="none">
                          <a href="./selenium/index.html" title="selenium">selenium</a>
            </li>
                  <li class="none">
                          <a href="./jmeter/index.html" title="jmeter">jmeter</a>
            </li>
          </ul>
                                                                                                                   <a href="http://www.softwaresano.com/" title="pimpam" class="poweredBy">
        <script type="text/javascript" src="http://www.softwaresano.com/widgets/builtBy.php"></script><script type="text/javascript" src="/widgets/builtBy.php"></script>
      </a>
                       
        
            </div>
    </div>
    <div id="bodyColumn">
      <div id="contentBox">
        <!-- Generado con el arquetipo: standalone-archetype --><!-- http://pimpam.googlecode.com --><div class="section"><h2>Verificaci&#xf3;n descarga<a name="Verificacin_descarga"></a></h2><!-- ~~~~~~~~~~ --><p>Antes de proceder a la instalaci&#xf3;n de <b>develenv</b> hay que comprobar la integridad de la descarga utilizando MD5. Para ello se debejen ejecutar los siguientes comandos:</p><div class="source"><pre>root@ironman:/tmp$ # Se calcula el md5 del fichero descargado
root@ironman:/tmp$ md5sum <?php echo $downloadArtifact;?> &gt; md5calculated
root@ironman:/tmp$ #Se obtiene el md5 que hay publicado en http://downloads.softwaresano.com/develenv/<?php echo $downloadArtifact;?>.md5 
root@ironman:/tmp$ wget http://downloads.softwaresano.com/develenv/<?php echo $downloadArtifact;?>.md5  
root@ironman:/tmp$ #Se calcula la diferencia entre el md5 calculado y el descargado
root@ironman:/tmp$ diff <?php echo $downloadArtifact;?>.md5 md5calculated 
root@ironman:/tmp$ #Si no hay diferencias entonces la descarga ha sido correcta</pre></div></div>
      </div>
    </div>
    <div class="clear">
      <hr/>
    </div>
    <div id="footer">
      <div class="xright">Copyright &#169;                    2011
                        <a href="http://develenv.softwaresano.com">SoftwareSano</a>.
            All Rights Reserved.      
        
      </div>
      <div class="clear">
        <hr/>
      </div>
    </div>
  <script type="text/javascript" src="http://www.softwaresano.com/widgets/foot.php"></script><script type="text/javascript" src="/widgets/foot.php"></script><script type="text/javascript" src="http://www.softwaresano.com/widgets/foot.php"></script><script type="text/javascript" src="/widgets/foot.php"></script></body>
</html>
