<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Generated by Apache Maven Doxia at 17-ene-2012 -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>develenv -
   <?php
      $develenvVersion=exec('cat ../index.html |grep "projectVersion"|sed s:".*\: ":"":g|sed s:"<.*":"":g');
     echo  $develenvVersion;
   ?></title>
    <style type="text/css" media="all">
      @import url("/css/maven-base.css");
      @import url("/css/maven-theme.css");
      @import url("/css/site.css");
    </style>
    <link rel="stylesheet" href="/docs/css/print.css" type="text/css" media="print" />
      <meta name="author" content="Carlos Enrique Gómez Gómez" />
    <meta name="Date-Revision-yyyymmdd" content="20120117" />
    <meta http-equiv="Content-Language" content="es" />
                                                    
<script type="text/javascript">var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-8116005-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
                                                        
<link rel="shortcut icon" href="http://pimpam.googlecode.com/files/favicon.ico"/>
                      
        </head>
  <body class="composite">
    <div id="banner">
                        <a href="http://www.softwaresano.com" id="bannerLeft">
                                                <script type="text/javascript" src="http://www.softwaresano.com/widgets/head.php"></script><script type="text/javascript" src="/widgets/head.php"></script>
                </a>
                    <div class="clear">
        <hr/>
      </div>
    </div>
    <div id="breadcrumbs">
            
        
                <div class="xleft">
        <span id="publishDate">Publicado el:  <?php
        $publishDate=exec('cat ../index.html |grep "Publicado el:"|sed s:".*\: ":"":g|sed s:"<.*":"":g');
        echo  $publishDate;?></span>
                  &nbsp;| <span id="projectVersion">Versión:<?php
echo $develenvVersion;
?></span>
                      </div>
            <div class="xright">                    <a href="/docs/team-list.html" title="Contacto">Contacto</a>
            |
                        <a href="/docs/.." title="Blog">Blog</a>
            |
                        <a href="/docs/repositories.html" title="Repositorios de componentes">Repositorios de componentes</a>
            |
                        <a href="/docs//sites/" class="externalLink" title="Sites">Sites</a>
            |
                        <a href="/docs//hudson/" class="externalLink" title="Jenkins">Jenkins</a>
            |
                        <a href="/docs//sonar" class="externalLink" title="Sonar">Sonar</a>
            |
                        <a href="/docs//nexus" class="externalLink" title="Nexus">Nexus</a>
            |
                        <a href="/docs/selenium/index.html" title="Selenium">Selenium</a>
              
        
      </div>
      <div class="clear">
        <hr/>
      </div>
    </div>
    <div id="leftColumn">
      <div id="navcolumn">
             
        
                                <h5>Descargas</h5>
                  <ul>
                  <li class="none">
                          <a href="/docs/downloads/releases.html" title="Releases">Releases</a>
            </li>
                  <li class="none">
                          <a href="/docs/downloads/snapshots.html" title="Snapshot">Snapshot</a>
            </li>
                  <li class="none">
                          <a href="/docs/virtualMachines.html" title="Máquina Virtual con develenv">Máquina Virtual con develenv</a>
            </li>
                  <li class="none">
                          <a href="/docs/changes-report.html" title="Release Notes">Release Notes</a>
            </li>
                  <li class="none">
                          <a href="/docs/license.html" title="Licencia">Licencia</a>
            </li>
          </ul>
                       <h5>develenv</h5>
                  <ul>
                  <li class="none">
                          <a href="/docs/index.html" title="Introducción">Introducción</a>
            </li>
                  <li class="none">
                          <a href="/docs/development.html" title="Compilación">Compilación</a>
            </li>
                  <li class="none">
                          <a href="/docs/installation.html" title="Instalación">Instalación</a>
            </li>
                  <li class="none">
                          <a href="/docs/administrationGuide.html" title="Manual del administrador">Manual del administrador</a>
            </li>
                  <li class="none">
                          <a href="/docs/developerGuide.html" title="Guía del desarrollador">Guía del desarrollador</a>
            </li>
                  <li class="none">
                          <a href="/docs/plugins.html" title="Plugins">Plugins</a>
            </li>
                  <li class="none">
                          <a href="/docs/samples.html" title="Ejemplos">Ejemplos</a>
            </li>
                  <li class="none">
                          <a href="/docs/improvements.html" title="Futuros desarrollos">Futuros desarrollos</a>
            </li>
          </ul>
                       <h5>Desarrollo</h5>
                  <ul>
                  <li class="none">
                          <a href="/docs/source-repository.html" title="Fuentes">Fuentes</a>
            </li>
                  <li class="none">
                          <a href="/docs/integration.html" title="Integración continua">Integración continua</a>
            </li>
                  <li class="none">
                          <a href="/docs/changelog.html" title="Control de cambios">Control de cambios</a>
            </li>
                  <li class="none">
                          <a href="/docs/improvements.html" title="Futuras Mejoras">Futuras Mejoras</a>
            </li>
          </ul>
                       <h5>Documentación del proyecto</h5>
                  <ul>
                                                                                                                                                                                                                                                                                            <li class="collapsed">
                          <a href="/docs/project-info.html" title="Información del proyecto">Información del proyecto</a>
                  </li>
                                                                                                                                            <li class="collapsed">
                          <a href="/docs/project-reports.html" title="Informes del proyecto">Informes del proyecto</a>
                  </li>
          </ul>
                                 <h5>Módulos</h5>
                  <ul>
                  <li class="none">
                          <a href="/docs/developer/index.html" title="developer">developer</a>
            </li>
                  <li class="none">
                          <a href="/docs/nexus/index.html" title="nexus">nexus</a>
            </li>
                  <li class="none">
                          <a href="/docs/sonar/index.html" title="sonar">sonar</a>
            </li>
                  <li class="none">
                          <a href="/docs/jenkins/index.html" title="jenkins">jenkins</a>
            </li>
                  <li class="none">
                          <a href="/docs/selenium/index.html" title="selenium">selenium</a>
            </li>
                  <li class="none">
                          <a href="/docs/jmeter/index.html" title="jmeter">jmeter</a>
            </li>
                  <li class="none">
                          <a href="/docs/soapui/index.html" title="soapui">soapui</a>
            </li>
          </ul>
                                                                                                                   <a href="http://www.softwaresano.com/" title="softwaresano" class="poweredBy">
        <img class="poweredBy"  alt="softwaresano" src="http://pimpam.googlecode.com/files/builtByPimpam.png"    />
      </a>
                       
        
            </div>
    </div>
    <div id="bodyColumn">
      <div id="contentBox">
        <!-- Generado con el arquetipo: standalone-archetype --><!-- http://www.softwaresano.com --><div class="section"><h2>sites<a name="sites"></a></h2><!-- ~~~ --><p>Sites de los jobs generados por Jenkins</div>
<pre><img src="/icons/blank.gif" alt="Icon "> <a href="?C=N;O=A">Name</a>                                  <a href="?C=M;O=A">Last modified</a>      <a href="?C=S;O=A">Size</a>  <a href="?C=D;O=A">Description</a><hr><img src="/icons/back.gif" alt="[DIR]"> <a href="/">Parent Directory</a>                                           -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="plugins/">plugins/</a>                              17-Jan-2012 13:13    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="ironman1/">ironman1/</a>                             17-Jan-2012 13:27    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="developer/">developer/</a>                            17-Jan-2012 13:11    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="com.softwaresano.examples/">com.softwaresano.examples/</a>            17-Jan-2012 13:29    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="com.softwaresano.examples.calculator/">com.softwaresano.examples.calculator/</a> 17-Jan-2012 13:37    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="com.softwaresano.develenv/">com.softwaresano.develenv/</a>            17-Jan-2012 13:33    -   
<img src="/icons/folder.gif" alt="[DIR]"> <a href="com.softwaresano.archetypes/">com.softwaresano.archetypes/</a>          17-Jan-2012 13:35    -   
<img src="/docs/icons/xml.png" alt="[   ]"> <a href="archetype-catalog.xml">archetype-catalog.xml</a>                 17-Jan-2012 13:14   25   
<hr></pre>
<div id="footer">
      <div class="xright">
              Copyright &#169;                    2012
                        <a href="http://develenv.softwaresano.com">SoftwareSano</a>.
            All Rights Reserved.      
        
                  </div>
      <div class="clear">
        <hr/>
      </div>
    </div>
  <script type="text/javascript" src="http://www.softwaresano.com/widgets/foot.php"></script><script type="text/javascript" src="/widgets/foot.php"></script><script type="text/javascript" src="http://www.softwaresano.com/widgets/foot.php"></script><script type="text/javascript" src="/widgets/foot.php"></script></body>
</html>
